version: '3.8'
services:
  kanata:
    container_name: kanata
    restart: always
    build: .
    networks:
      - kanata
    volumes:
      - type: bind
        read_only: true
        target: /app/kanata/config.yml
        source: ./config.yml

  etcd0:
    image: quay.io/coreos/etcd
    ports:
      - 2379
    volumes:
      - etcd0_data:/etcd_data
    command:
      - etcd
      - -name
      - etcd0
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - http://etcd0:2379
      - -listen-client-urls
      - http://0.0.0.0:2379
      - -initial-advertise-peer-urls
      - http://etcd0:2380
      - -listen-peer-urls
      - http://0.0.0.0:2380
      - -initial-cluster
      - etcd0=http://etcd0:2380,http://etcd1:2380,http://etcd2:2380

  etcd1:
    image: quay.io/coreos/etcd
    ports:
      - 2379
    volumes:
      - etcd0_data:/etcd_data
    command:
      - etcd
      - -name
      - etcd1
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - http://etcd1:2379
      - -listen-client-urls
      - http://0.0.0.0:2379
      - -initial-advertise-peer-urls
      - http://etcd1:2380
      - -listen-peer-urls
      - http://0.0.0.0:2380
      - -initial-cluster
      - etcd0=http://etcd0:2380,http://etcd1:2380,http://etcd2:2380

  etcd2:
    image: quay.io/coreos/etcd
    ports:
      - 2379
    volumes:
      - etcd0_data:/etcd_data
    command:
      - etcd
      - -name
      - etcd2
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - http://etcd2:2379
      - -listen-client-urls
      - http://0.0.0.0:2379
      - -initial-advertise-peer-urls
      - http://etcd2:2380
      - -listen-peer-urls
      - http://0.0.0.0:2380
      - -initial-cluster
      - etcd0=http://etcd0:2380,http://etcd1:2380,http://etcd2:2380

networks:
  kanata:
    internal: true

volumes:
  etcd0_data:
  etcd1_data:
  etcd2_data:
