name: Lint on Commit
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'feature/**'
      - 'bug/gh-**'
      - 'issue/gh-**'
      - staging
      - master

    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - 'assets/**'
      - 'docker/**'
      - '.idea/**'
      - '.dockerignore'
      - '.gitignore'
      - '**.md'
      - 'LICENSE'
      - 'renovate.json'
  push:
    branches:
      - 'feature/**'
      - 'bug/gh-**'
      - 'issue/gh-**'
      - staging
      - master

    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - 'assets/**'
      - 'docker/**'
      - '.idea/**'
      - '.dockerignore'
      - '.gitignore'
      - '**.md'
      - 'LICENSE'
      - 'renovate.json'
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install dependencies
        run: go mod download && go get

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-${{ matrix.go-version }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.go-version }}-go-

      - name: Build project to see if it compiles
        run: make build

      - name: Format project for any formatting to apply
        run: make fmt

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          args: --issues-exit-code=1
          only-new-issues: false
          skip-go-installation: true
          skip-pkg-cache: true
          skip-build-cache: true

      - name: Check if git status is dirty
        id: git_status
        if: ${{ github.event_name == 'push' }}
        run: |
          if [ -n "$(git status --porcelain)" ]; then
              echo '::set-output name=STATUS_DIRTY::true'
          else
            echo '::set-output name=STATUS_DIRTY::false'
          fi

      - name: Commit changes (if dirty)
        if: contains(steps.git_status.outputs.STATUS_DIRTY, 'true') && ${{ github.event_name == 'push' }}
        run: |
          git config --global user.name "Noel[bot]"
          git config --global user.email "noelbot@users.noreply.github.com"
          git config --global committer.email "cutie@floofy.dev"
          git config --global committer.name "Noel"
          
          git add .
          git commit -m "chore: format project :sparkles:"
          git push -u origin master
